[0.目录](../0.目录.md)
# 4.6  多次失败
到目前为止，我们已经隐式地假设计算将仅凭单个失败值失败。例如，我们的应用程序可能会因IOException或NumberFormatException而失败，但不会同时因两个异常而失败。
在简单的程序代码中，这是一个合理的假设。我们一次评估一个语句，并且在第一次引发异常时，我们停止评估其他语句，并将该异常传播到调用堆栈中。
但是有几种方法可以打破这种假设。
首先，如果我们的程序是并发的，则可能同时执行我们程序的多个部分。我们将很快谈论ZIO对并发编程的支持，但就目前而言，一个简单的示例就足够了。
假设我们需要创建一个包含客户数据的表。一些数据存在于我们的西海岸数据中心中，其余数据存储在东海岸数据中心中。为了减少延迟，我们将请求并行发送到每个数据中心。但不幸的是，我们两个请求均失败，错误分别为e1和e2。
我们应该返回什么错误？在简单的模型中，计算只能返回一个失败，我们被迫丢弃e1或e2，丢弃对调用者可能很重要的信息。
其次，即使在纯顺序程序中，也有可能出现多个故障。
```
  lazy val example =
    try {
      throw new Exception("Error using file!")
    } finally {
      throw new Exception("Couldn't close file!")
    }
```

在此代码段中，我们正在执行引发异常的代码，也许正在处理文件。 无论我们的代码如何终止，我们都在使用Scala的try / finally语法来确保终结器运行，也许是为了关闭文件。 但是终结器本身会引发异常！ 在这种情况下，应将哪个异常传播到更高级别的应用程序？
除了成为令人困惑的来源之外，尤其是当存在多个这样的嵌套语句时，我们不可避免地还会丢弃信息。
为了处理这种情况，ZIO除了上面讨论的原因外，还包括Cause的另外两个子类型：

```
  sealed trait Cause[+E]
  object Cause {
    final case class Die(t: Throwable) extends Cause[Nothing]
    final case class Fail[+E](e: E) extends Cause[E]
    final case class Both[+E](left: Cause[E], right: Cause[E]) extends Cause[E]
    final case class Then[+E](left: Cause[E], right: Cause[E]) extends Cause[E]
  }
```

Both数据类型代表两种同时发生的失败原因。例如，如果要描述来自两个数据中心的客户数据的查询结果，则应使用`Cause.Both（e1，e2）`。  
Then数据类型表示两种故障原因，它们依次发生。例如，如果我们正在使用文件，并且在使用文件和关闭文件时均发生故障，则可以使用`Cause.Then（useFailure，releaseFailure）`。
请注意，“双向”和“然后”中的原因本身可以包含多个原因，因此“原因”使我们不仅可以代表两个故障，而且可以任意代表许多故障，同时保留有关这些故障的并行和顺序结构的信息。
